version: "2.4"

services:
  exit0:
    image: alpine
    command: sh -c "echo 'sleeping 1 second'; sleep 1; echo 'exiting with 0'; exit 0"

  exit0-re:
    image: alpine
    restart: always
    command: sh -c "echo 'sleeping 1 second'; sleep 1; echo 'exiting with 0'; exit 0"

  exit1:
    image: alpine
    command: sh -c "echo 'sleeping 1 second'; sleep 1; echo 'exiting with 1'; exit 1"

  exit7:
    image: alpine
    command: sh -c "echo 'sleeping 1 second'; sleep 1; echo 'exiting with 7'; exit 7"

  scale:
    image: alpine
    scale: 3
    command: sh -c 'echo "Started"; sleep 99999'

  counter:
    image: alpine
    command: sh -c 'echo "Started"; i=0; while true; do echo "Line $$i"; sleep 1; i=$$(( i + 1 )); done'

  final:
    image: alpine
    command: sh -c 'echo "Started"; sleep 99999'

